"""Add car_type field to OfficialCar model

Revision ID: 117632368b77
Revises: 32c241e131f6
Create Date: 2025-03-14 16:09:11.667746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117632368b77'
down_revision = '32c241e131f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_type', sa.String(length=100), nullable=True, comment='车型'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_cars', schema=None) as batch_op:
        batch_op.drop_column('car_type')

    # ### end Alembic commands ###
