"""Add application_time and other fields to CarMaintenanceRecord

Revision ID: 1429d23e5168
Revises: 58421c3fa678
Create Date: 2025-03-17 15:02:02.653343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1429d23e5168'
down_revision = '58421c3fa678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_maintenance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_time', sa.Date(), nullable=False, comment='申请时间'))
        batch_op.add_column(sa.Column('car_type', sa.String(length=100), nullable=True, comment='车型'))
        batch_op.add_column(sa.Column('plate_number', sa.String(length=20), nullable=False, comment='车牌号'))
        batch_op.add_column(sa.Column('driver', sa.String(length=50), nullable=True, comment='驾驶员'))
        batch_op.add_column(sa.Column('sender', sa.String(length=50), nullable=True, comment='送修人'))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True, comment='送修原因'))
        batch_op.add_column(sa.Column('completion_time', sa.Date(), nullable=True, comment='完成时间'))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'))
        batch_op.drop_column('maintenance_time')
        batch_op.drop_column('maintenance_type')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('maintenance_items')
        batch_op.drop_column('current_mileage')
        batch_op.drop_column('invoice_file')
        batch_op.drop_column('responsible_person')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_maintenance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_person', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('invoice_file', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('current_mileage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_items', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('maintenance_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('maintenance_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('completion_time')
        batch_op.drop_column('reason')
        batch_op.drop_column('sender')
        batch_op.drop_column('driver')
        batch_op.drop_column('plate_number')
        batch_op.drop_column('car_type')
        batch_op.drop_column('application_time')

    # ### end Alembic commands ###
