"""Rename approver_name to approver in VehicleExit model

Revision ID: 21400eedb5f2
Revises: rename_approver_to_approver_name
Create Date: 2025-03-13 08:01:52.876927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21400eedb5f2'
down_revision = 'rename_approver_to_approver_name'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_exit_temp')
    with op.batch_alter_table('vehicle_exit', schema=None) as batch_op:
        batch_op.drop_column('approver_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_exit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_name', sa.VARCHAR(length=50), nullable=True))

    op.create_table('vehicle_exit_temp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exit_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('initiator', sa.VARCHAR(length=50), nullable=True),
    sa.Column('certificate_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('plate_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('driver_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('logistics_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('logistics_company', sa.VARCHAR(length=100), nullable=True),
    sa.Column('logistics_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('company', sa.VARCHAR(length=100), nullable=True),
    sa.Column('item_category', sa.VARCHAR(length=20), nullable=True),
    sa.Column('destination', sa.VARCHAR(length=200), nullable=True),
    sa.Column('items', sa.TEXT(), nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=200), nullable=True),
    sa.Column('exit_time', sa.DATETIME(), nullable=True),
    sa.Column('expected_return_time', sa.DATETIME(), nullable=True),
    sa.Column('actual_return_time', sa.DATETIME(), nullable=True),
    sa.Column('confirmed_exit_time', sa.DATETIME(), nullable=True),
    sa.Column('reviewer', sa.VARCHAR(length=50), nullable=True),
    sa.Column('issuer', sa.VARCHAR(length=50), nullable=True),
    sa.Column('approver_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('guard', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('approved_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
