"""change is_business_car field from Boolean to String

Revision ID: 32c241e131f6
Revises: 6ded604d8d50
Create Date: 2025-03-14 09:28:26.103120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c241e131f6'
down_revision = '6ded604d8d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_cars', schema=None) as batch_op:
        batch_op.alter_column('is_business_car',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_cars', schema=None) as batch_op:
        batch_op.alter_column('is_business_car',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
