"""Add Monitor model and update Room model

Revision ID: 6ccda2631b90
Revises: 4501f111c797
Create Date: 2024-03-06 09:48:17.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccda2631b90'
down_revision = '4501f111c797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_monitor_room_id'),
    sa.PrimaryKeyConstraint('id', name='pk_monitor'),
    sa.UniqueConstraint('employee_id', name='uq_monitor_employee_id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_dormitory_id', type_='foreignkey')
        batch_op.drop_column('facilities')
        batch_op.add_column(sa.Column('floor', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('room_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_foreign_key('fk_room_dormitory_id', 'dormitories', ['dormitory_id'], ['id'])
        batch_op.create_foreign_key('fk_room_monitor_id', 'monitors', ['monitor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_monitor_id', type_='foreignkey')
        batch_op.drop_constraint('fk_room_dormitory_id', type_='foreignkey')
        batch_op.drop_column('monitor_id')
        batch_op.drop_column('description')
        batch_op.drop_column('floor')
        batch_op.add_column(sa.Column('facilities', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_room_dormitory_id', 'dormitories', ['dormitory_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('room_number',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.drop_table('monitors')
    # ### end Alembic commands ###
