"""add created_by, updated_by, and scrapped_by fields to OfficialCar model

Revision ID: 6ded604d8d50
Revises: becb69c6387e
Create Date: 2025-03-14 09:22:21.718754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ded604d8d50'
down_revision = 'becb69c6387e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scrapped_by', sa.Integer(), nullable=True, comment='报废操作人ID'))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_cars', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('scrapped_by')

    # ### end Alembic commands ###
