"""add_official_car_tables

Revision ID: 7dd8e8535975
Revises: 520ce76219a9
Create Date: 2025-03-14 09:01:43.603862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd8e8535975'
down_revision = '520ce76219a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True, comment='序号'),
    sa.Column('card_number', sa.String(length=50), nullable=True, comment='卡片编号'),
    sa.Column('asset_number', sa.String(length=50), nullable=False, comment='资产编号'),
    sa.Column('brand', sa.String(length=50), nullable=True, comment='品牌'),
    sa.Column('asset_description', sa.String(length=200), nullable=True, comment='资产描述'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='规格型号'),
    sa.Column('original_value', sa.Float(), nullable=True, comment='原值'),
    sa.Column('is_business_car', sa.Boolean(), nullable=True, comment='是否经营用车'),
    sa.Column('plate_number', sa.String(length=20), nullable=True, comment='车牌号'),
    sa.Column('car_model', sa.String(length=100), nullable=True, comment='车辆型号'),
    sa.Column('registration_time', sa.DateTime(), nullable=True, comment='登记时间'),
    sa.Column('seat_count', sa.Integer(), nullable=True, comment='座位数'),
    sa.Column('displacement', sa.String(length=50), nullable=True, comment='排气量'),
    sa.Column('responsible_person', sa.String(length=50), nullable=True, comment='责任人'),
    sa.Column('usage_nature', sa.String(length=50), nullable=True, comment='使用性质'),
    sa.Column('vehicle_license', sa.String(length=255), nullable=True, comment='车辆行驶证文件路径'),
    sa.Column('status', sa.Enum('idle', 'dispatched', 'borrowed', 'maintenance', 'scrapped', name='carstatus'), nullable=True, comment='车辆状态'),
    sa.Column('is_scrapped', sa.Boolean(), nullable=True, comment='是否报废'),
    sa.Column('scrap_time', sa.DateTime(), nullable=True, comment='报废时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车辆ID'),
    sa.Column('fuel_type', sa.String(length=20), nullable=True, comment='类型：gas（加油）, charge（充电）'),
    sa.Column('fuel_time', sa.DateTime(), nullable=False, comment='加油充值时间'),
    sa.Column('fuel_location', sa.String(length=100), nullable=True, comment='加油充值地点'),
    sa.Column('fuel_amount', sa.Float(), nullable=True, comment='加油量/充电量'),
    sa.Column('current_mileage', sa.Float(), nullable=True, comment='当前里程'),
    sa.Column('cost', sa.Float(), nullable=True, comment='费用'),
    sa.Column('invoice_number', sa.String(length=50), nullable=True, comment='发票号码'),
    sa.Column('invoice_file', sa.String(length=255), nullable=True, comment='发票文件路径'),
    sa.Column('responsible_person', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['official_cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车辆ID'),
    sa.Column('maintenance_type', sa.String(length=20), nullable=True, comment='类型：maintenance（保养）, repair（维修）'),
    sa.Column('maintenance_time', sa.DateTime(), nullable=False, comment='维修保养时间'),
    sa.Column('maintenance_location', sa.String(length=100), nullable=True, comment='维修保养地点'),
    sa.Column('maintenance_items', sa.Text(), nullable=True, comment='维修保养项目'),
    sa.Column('current_mileage', sa.Float(), nullable=True, comment='当前里程'),
    sa.Column('cost', sa.Float(), nullable=True, comment='费用'),
    sa.Column('invoice_number', sa.String(length=50), nullable=True, comment='发票号码'),
    sa.Column('invoice_file', sa.String(length=255), nullable=True, comment='发票文件路径'),
    sa.Column('responsible_person', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['official_cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车辆ID'),
    sa.Column('applicant', sa.String(length=50), nullable=False, comment='申请人'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='部门'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('expected_end_time', sa.DateTime(), nullable=False, comment='预计结束时间'),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True, comment='实际结束时间'),
    sa.Column('passengers', sa.Integer(), nullable=True, comment='乘车人数'),
    sa.Column('destination', sa.String(length=100), nullable=True, comment='目的地'),
    sa.Column('purpose', sa.String(length=200), nullable=True, comment='用车事由'),
    sa.Column('start_mileage', sa.Float(), nullable=True, comment='起始里程'),
    sa.Column('end_mileage', sa.Float(), nullable=True, comment='结束里程'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending（待审核）, approved（已批准）, rejected（已拒绝）, completed（已完成）'),
    sa.Column('approver', sa.String(length=50), nullable=True, comment='审批人'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['official_cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_usage_records')
    op.drop_table('car_maintenance_records')
    op.drop_table('car_fuel_records')
    op.drop_table('official_cars')
    # ### end Alembic commands ###
