"""Add car_usage_records table with departure_date column

Revision ID: be6420278a8e
Revises: 117632368b77
Create Date: 2025-03-15 11:25:24.688085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6420278a8e'
down_revision = '117632368b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_number', sa.String(length=20), nullable=False, comment='使用车牌号'))
        batch_op.add_column(sa.Column('departure_date', sa.Date(), nullable=False, comment='出车日期'))
        batch_op.add_column(sa.Column('departure_time', sa.Time(), nullable=False, comment='出车时间'))
        batch_op.add_column(sa.Column('departure_mileage', sa.Float(), nullable=True, comment='出车里程'))
        batch_op.add_column(sa.Column('destination_purpose', sa.String(length=200), nullable=True, comment='出车去向及事由'))
        batch_op.add_column(sa.Column('return_time', sa.DateTime(), nullable=True, comment='收车时间'))
        batch_op.add_column(sa.Column('return_mileage', sa.Float(), nullable=True, comment='收车里程'))
        batch_op.add_column(sa.Column('usage_duration', sa.String(length=20), nullable=True, comment='使用时长'))
        batch_op.add_column(sa.Column('driver', sa.String(length=50), nullable=True, comment='驾驶员'))
        batch_op.add_column(sa.Column('refueling', sa.Boolean(), nullable=True, comment='加油'))
        batch_op.add_column(sa.Column('maintenance', sa.String(length=200), nullable=True, comment='维修'))
        batch_op.add_column(sa.Column('toll_fee', sa.String(length=50), nullable=True, comment='过路过桥费'))
        batch_op.add_column(sa.Column('parking_fee', sa.String(length=50), nullable=True, comment='停车费'))
        batch_op.add_column(sa.Column('accident_violation', sa.String(length=200), nullable=True, comment='交通事故、违章'))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'))
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('passengers',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('start_mileage')
        batch_op.drop_column('start_time')
        batch_op.drop_column('expected_end_time')
        batch_op.drop_column('applicant')
        batch_op.drop_column('end_mileage')
        batch_op.drop_column('phone')
        batch_op.drop_column('status')
        batch_op.drop_column('approver')
        batch_op.drop_column('purpose')
        batch_op.drop_column('remarks')
        batch_op.drop_column('destination')
        batch_op.drop_column('actual_end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_end_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('approver', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_mileage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('applicant', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('expected_end_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_mileage', sa.FLOAT(), nullable=True))
        batch_op.alter_column('passengers',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('accident_violation')
        batch_op.drop_column('parking_fee')
        batch_op.drop_column('toll_fee')
        batch_op.drop_column('maintenance')
        batch_op.drop_column('refueling')
        batch_op.drop_column('driver')
        batch_op.drop_column('usage_duration')
        batch_op.drop_column('return_mileage')
        batch_op.drop_column('return_time')
        batch_op.drop_column('destination_purpose')
        batch_op.drop_column('departure_mileage')
        batch_op.drop_column('departure_time')
        batch_op.drop_column('departure_date')
        batch_op.drop_column('plate_number')

    # ### end Alembic commands ###
