"""Add employee_id, name, department, phone fields to User model

Revision ID: f4936199e7df
Revises: fdab36fc05fb
Create Date: 2025-03-06 09:16:13.192858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4936199e7df'
down_revision = 'fdab36fc05fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True))
        batch_op.create_unique_constraint(None, ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')
        batch_op.drop_column('department')
        batch_op.drop_column('name')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
